### ISSUE TITLE
Parameterize Display strings in Gatekeeper

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/js-tools#110]
Custom strings should be passable to replace default display strings.

- [ ] [Login message](https://github.com/onaio/js-tools/blob/master/packages/gatekeeper/src/components/login.tsx#L22)
- [ ] [Callback Success message](https://github.com/onaio/js-tools/blob/master/packages/gatekeeper/src/components/callback.tsx#L83)
- [ ] [Please Wait message](https://github.com/onaio/js-tools/blob/master/packages/gatekeeper/src/components/callback.tsx#L67)
- [ ] [Callback Error message](https://github.com/onaio/js-tools/blob/master/packages/gatekeeper/src/components/callback.tsx#L58)
- [ ] [404 Error message](https://github.com/onaio/js-tools/blob/master/packages/gatekeeper/src/components/callback.tsx#L49)

**Comment by moshthepitt** [comment]
@cKellyDesign I think that this has already been implemented [here](https://github.com/onaio/js-tools/blob/master/packages/gatekeeper/src/components/callback/utils.tsx).

If you agree, let us close this one.
