### ISSUE TITLE
New Package: Add Google Analytics HOC

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/js-tools#113]
Currently we have two versions of the same Higher Order Component for page-view tracking with Google Analytics (using [react-ga](https://github.com/react-ga/react-ga)), one [in GRP](https://github.com/onaio/grp-frontend/blob/master/src/components/WithGATracker.js) and one [in Reveal](https://github.com/onaio/reveal-frontend/blob/master/src/components/page/WithGATracker/index.tsx). These should be standardized and optimized here as a package and imported into existing and future implementations of Google Analytics in React FE projects.

### MVP Feature Requests
- [ ] HOC which calls page-views whenever the URL changes
- [ ] Decouple the HOC from Router props (use `window.location` to define the page URL)
- [ ] Optionally set GA dimensions before tracking the page
- [ ] Name the package / component something better than `WithGATracker`

### Blue Sky Requests
- [ ] Typescript please 🙏 
- [ ] Gatekeeper integration (to track logins and logouts)
- [ ] GA dimension redux store

**Comment by moshthepitt** [comment]
@cKellyDesign @JohnMwashuma does the HOV necessarily need to be wrapped around every single component, like we have done here https://github.com/onaio/reveal-frontend/blob/master/src/App/App.tsx ?

I mean I see how that can be flexible if you want some components to have it and others not to.

However, for large projects (like Reveal), I think that this is cumbersome and I am wondering whether it can just be wrapped around ONE THING?  e.g. around `<App/>` or as some kind of provider?

**Comment by cKellyDesign** [comment]
@moshthepitt I am definitely open to refactoring, especially to avoid the remounting we are seeing in Reveal and would also like to make it DRYer 👍

**Comment by JohnMwashuma** [comment]
@moshthepitt No just wrap the `<App />` component like this: https://github.com/onaio/grp-frontend/blob/ed1c747e100ca0f1c02fd3a6b1bb117cf6d0473b/src/index.js#L19
Once this is done you should be able to receive GA events for every page clicked.

**Comment by moshthepitt** [comment]
Thanks @JohnMwashuma

**Comment by cKellyDesign** [comment]
> No just wrap the `<App />` component like this

The issue we are facing in Reveal is all the child components un-mounting when the url changed (even if the two routes are handled by the same component), so as long as we check to make sure that's not happening then I am a big fan of this approach 👍
