### ISSUE TITLE
Adding .github templates 

### ISSUE THREAD

**Issue by p-netm** [onaio/js-tools#127]
- This is one repo that is bound to have a lot of feature requests and bug fixes. Might be a good idea to add templates for the aforementioned

**Comment by moshthepitt** [comment]
Good idea!  I have assigned to you.  @DavisRayM did this recently in another repo if you need help

**Comment by cKellyDesign** [comment]
Yes, let's do this! 🙌

**Comment by DavisRayM** [comment]
You can use our templates as inspiration 😺 have a look [here](https://github.com/onaio/onadata/pull/1750).

**Comment by DavisRayM** [comment]
Would be better to use the new Issue Template creation flow though. Has way better handling (switches templates for Bug reports / Feature request automatically). You can read more about it [here](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository).
