### ISSUE TITLE
New Package: ona-utils

### ISSUE THREAD

**Issue by moshthepitt** [onaio/js-tools#133]
This is a proposal to have a new package that holds the tiny little helper functions, type definitions, etc that we often re-use but don't make sense to be individual packages.

List so far:

- [x] [FlexObject](https://github.com/onaio/reveal-frontend/blob/acdc40f222c9a3bf281c5f2e90ffe180ba34f853/src/helpers/utils.tsx#L41)  ([more discussion](https://github.com/onaio/js-tools/issues/133#issuecomment-588850533))
- [ ] [generateNameSpacedUUID](https://github.com/onaio/reveal-frontend/blob/acdc40f222c9a3bf281c5f2e90ffe180ba34f853/src/helpers/utils.tsx#L646)
- [x] [UpdateType](https://github.com/onaio/reveal-frontend/blob/acdc40f222c9a3bf281c5f2e90ffe180ba34f853/src/helpers/utils.tsx#L458)
- [x] [percentage](https://github.com/onaio/reveal-frontend/blob/acdc40f222c9a3bf281c5f2e90ffe180ba34f853/src/helpers/utils.tsx#L68)
- [x] [Result class](https://khalilstemmler.com/articles/enterprise-typescript-nodejs/handling-errors-result-class/)

**Comment by moshthepitt** [comment]
@cKellyDesign @p-netm please help add things to this list 🙏

**Comment by cKellyDesign** [comment]
Can we name the package `utils` so we install it as `@onaio/utils`?

**Comment by moshthepitt** [comment]
> Can we name the package utils so we install it as @onaio/utils?

Excellent idea

**Comment by p-netm** [comment]
>     * FlexObject

I just want to leave it here that what we call `FlexObject` is usually referred to as `Dictionary` in most of other well known ts projects.

**Comment by moshthepitt** [comment]
@p-netm Do you have a link handy for that?

**Comment by p-netm** [comment]
> @p-netm Do you have a link handy for that?

Not really but i what maybe i can offer is [this](https://github.com/onaio/js-tools/issues/133#issuecomment-588756267)
- [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cc94d809483a47c6e1a34c2fcebe9354d915edf5/types/apptimize__apptimize-web-sdk/index.d.ts#L8)
- [Mongo](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d857ed267144db6438b04cee94f1fa03198c4052/types/meteor/globals/mongo.d.ts#L88)
- [and here(steed)](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5344bfc80508c53a23dae37b860fb0c905ff7b24/types/steed/index.d.ts#L7)
- [whatever calidation is](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d30cbbd8cd8dbe5916a39f93ba07455da6921c34/types/calidation/index.d.ts#L9)
- And lodash too
These are just in the first 2 pages of the results.

**Comment by moshthepitt** [comment]
Nice, thanks.

These do indeed look similar

```ts
interface Dictionary<T> {
    [key: string]: T;
}

interface FlexObject {
    [key: string]: any;
}
```

**Comment by cKellyDesign** [comment]
Nice, i like this one best :)
```ts
interface Dictionary<T=any> {
    [key: string]: T;
}
```
