### ISSUE TITLE
Type Definition Error

### ISSUE THREAD

**Issue by kahummer** [onaio/js-tools#146]
**Describe the bug**
When replacing existing percentage util method with ona/utils a type error 
``` Type 'Result<string>' is not assignable to type 'string'.
  Type 'Failure' is not assignable to type 'string' ```
```
occurs

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot from 2020-03-16 19-58-25](https://user-images.githubusercontent.com/16018123/76782723-c7673400-67c1-11ea-913a-af377acf4cdf.png)

**Additional context**
After going into the types dts file and adding the type param to failure it works. I think this can be updated on js tools published.

**Comment by moshthepitt** [comment]
@kahummer I do not think that this is a bug.  In your usage (in the screenshot), you are expecting a string, but the function actually returns `Result<string>` which is actually not a string.  You need to change the code that uses `percentage` to work with `Result<string>`.

Additionally, read up on the `Result` type and contribute on the discussions around its introduction and usage.
