### ISSUE TITLE
🤔Discussion: Core Utility Packages as peerDependencies

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/js-tools#151]
**Is this a new feature or an enhancement?**
Enhancement / Optimization

**Is your feature request related to a problem? Please describe.**
Should `@onaio/utils` and `@onaio/react-utils` be peerDepencies of our other packages? 

**Describe the solution you'd like**
Would this make is so things like [`Dictionary`](https://github.com/onaio/js-tools/blob/master/packages/utils/src/types.ts#L14-L16) and [`percentage`](https://github.com/onaio/js-tools/blob/master/packages/utils/src/utils.ts#L9-L14) are referencing a single declaration globally throughout a project (which uses our `js-tool`'ing)?

**Comment by moshthepitt** [comment]
Why peer dependencies?

**Comment by cKellyDesign** [comment]
> Why peer dependencies?
 
@moshthepitt so that installing the package also installs the utils:  
```
👍 yarn add @onaio/session-reducer
```
without requiring the user to install the utils:
```
👎 yarn add @onaio/utils @onaio/session-reducer 
```

**Comment by moshthepitt** [comment]
@cKellyDesign I think that we should only do this for packages that actually use `@onaio/utils`.  I think something like `gatekeeper` does indeed need `Dictionary` from `@onaio/utils` but something like `@onaio/session-reducer` does not need any extra dependency, and we shouldn't force someone to install `@onaio/utils` when they just need/want `@onaio/session-reducer`  (for example).

It seems the only benefit is some convenience for us?  I'm not sure it is work it though.

**Comment by cKellyDesign** [comment]
Definitely only want to install them in packages which would use them.

> It seems the only benefit is some convenience for us? I'm not sure it is work it though.

If it's not worth the effort then we don't need to pursue :)

**Comment by moshthepitt** [comment]
> Definitely only want to install them in packages which would use them.

There is an issue for this https://github.com/onaio/js-tools/issues/142

**Comment by cKellyDesign** [comment]
Cool, I'm going to close this. one then :)
