### ISSUE TITLE
Add the gisidaLite component to Js-tools

### ISSUE THREAD

**Issue by p-netm** [onaio/js-tools#157]
**Is this a new feature or an enhancement?**
New Feature

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

The gisida lite mapping wrapper component  that at the moment resides on reveal FE should be moved here as a package.

**Additional context**

**Comment by kahummer** [comment]
Add a component that takes props: reactmapboxgl, mapBoxProps, mapComponents and layers
We can have these as the defaults. mapBoxProps and reactmapboxgl can be changed to allow additional map instance options
```  JSON
reactmapboxgl: {
   accessToken,
   attributionControl,
   customAttribution,
   injectCSS
},
mapBoxProps: Props & Events = {
    center,
    containerStyle: {
    mapHeight,
    mapWidth 
    }
    style: mapStyle,
  }; 
mapComponents: []  // will include things like ZoomControl, ScaleControl etc
  
layer: []
```

  
The component should render a default style and a basic layer from the default props.

Concerns:
After going through reveal's GisidaLite and holding discussions with other engineers. The current implementation in reveal may need some tweaks to use this component. The layers seem to be updating gradually causing undesired renders on the map. The workaround was setting a flag to state which is false by default then turning that to true once the map loads the style. By the time all this happens all the layers will be loaded thus rendering the layers as expected. 
Thoughts:
IMHO I think the layers update issue should be handled from the parent component so by the time we get to GisidLite everything is rendered once without introducing this complexity.
cc @moshthepitt @kelvin-muchiri

**Comment by moshthepitt** [comment]
@kahummer sounds good.  A PR (here or elsewhere) would be nice :)
