### ISSUE TITLE
Adding a package is not as straightforward

### ISSUE THREAD

**Issue by p-netm** [onaio/js-tools#99]
Seems like new contributors are having a hard time getting started, contributing. 

Maybe we can make the contribution process easier, 
- maybe add a doc that solely takes a contributor through a sample process of adding a component
- Or we could have a template that can be used, 
- !!?

**Comment by RayceeM** [comment]
I would suggest adding links to docs such as https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html and any related to js. I guess we should consider you should have some basic knowledge in js at least?

**Comment by moshthepitt** [comment]
@RayceeM PRs are welcome, and encouraged :)

**Comment by p-netm** [comment]
closing this, since it has been relatively inactive
